spring:
    application:
        name: Receiver-Service
    rabbitmq:
        host: ${RABBITMQ_IP:34.45.188.216}
        port: 5672
        username: ${RABBITMQ_USERNAME}
        password: ${RABBITMQ_PASSWORD}
