spring:
  application:
    name: Filter-Service
server:
  port: 8443
rabbit:
  mq:
    pre-filter-queue: "pre-filter"
    pre-filter-routing-key: "pre-filter-key"
    post-filter-queue: "post-filter"
    post-filter-routing-key: "post-filter-key"
    exchange: "exchange"

admin-key: a7Dg5zK9xH