spring:
  application:
    name: Filter-Service

  rabbitmq:
    host: ${RABBITMQ_IP:34.45.188.216}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      exchange: "exchange"

custom:
  rabbitmq:
    pre-filter-queue: "pre-filter"
    pre-filter-routing-key: "pre-filter-key"
    post-filter-queue: "post-filter"
    post-filter-routing-key: "post-filter-key"

admin-key: a7Dg5zK9xH

filter-service: ${PNS_URL:https://panic-notification-service-69887867641.us-east1.run.app}