server:
  port: ${PORT:8080}
  servlet:
    context-path: /Panic-Notification-Service

spring:
    application:
        name: Panic-Notification-Service

    datasource:
            url: ${DB_DATABASE:postgres}
            username: ${DB_USERNAME:username}
            password: ${DB_PASSWORD:password}
            driverClassName: org.postgresql.Driver
            hikari:
              minimum-idle: 2
              maximum-pool-size: 5
              data-source-properties:
                socketFactory: com.google.cloud.sql.postgres.SocketFactory
                cloudSqlInstance: panic-notification-system:us-central1:panicdb
                enableIamAuth: true
                sslmode: disable

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

admin-key: ${ADMIN_KEY:a7Dg5zK9xH}


